version: '3.4'

services:
  mikroservis1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mikroservis2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  mikroservis3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

